"""
The core question, done properly:

    Treat Argentina in 2022 and 2026 as the SUBJECT.
    Treat the rest of World Cup history as the CONTROL / baseline.
    Ask: how extreme is Argentina's penalty haul against that baseline?

Two independent lenses:
  1. Rate lens  -- Poisson test of Argentina's penalties-per-game vs the modern
     (VAR-era) tournament baseline rate. Done for 2022, 2026, and pooled.
  2. Record lens -- where does Argentina sit in the all-time distribution of
     "most penalties awarded to a single team in one World Cup"?

Run:  python src/baseline_comparison.py
Outputs: figures/*.png and reports/BASELINE_FINDINGS.md
"""

from pathlib import Path

import pandas as pd
from scipy import stats
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
FIG = ROOT / "figures"
REPORTS = ROOT / "reports"
FIG.mkdir(exist_ok=True)
REPORTS.mkdir(exist_ok=True)

ARG_BLUE = "#75AADB"
ARG_NAVY = "#2B3A67"
ACCENT = "#D64545"
GREY = "#9AA0A6"


def var_era_baseline() -> float:
    """Penalties per team-match across the VAR era (the fair modern reference)."""
    t = pd.read_csv(DATA / "tournament_penalty_totals.csv")
    v = t[t["var_era"] == "yes"]
    return v["total_penalties"].sum() / v["team_matches"].sum()


def poisson_row(label, pens, games, rate, provisional=False):
    lam = rate * games
    fold = pens / lam if lam else float("nan")
    p = stats.poisson.sf(pens - 1, lam)  # P(X >= pens)
    return {
        "label": label,
        "pens": pens,
        "games": games,
        "expected": lam,
        "fold": fold,
        "p": p,
        "provisional": provisional,
    }


def main():
    rate = var_era_baseline()
    subj = pd.read_csv(DATA / "argentina_subject.csv")
    recs = pd.read_csv(DATA / "team_tournament_penalty_records.csv")

    a22 = subj[subj["tournament"] == 2022].iloc[0]
    a26 = subj[subj["tournament"] == 2026].iloc[0]

    rows = [
        poisson_row("Argentina 2022", int(a22.pens_for), int(a22.games), rate),
        poisson_row("Argentina 2026 (provisional)", int(a26.pens_for), int(a26.games), rate, True),
        poisson_row(
            "Argentina 2022+2026 pooled",
            int(a22.pens_for) + int(a26.pens_for),
            int(a22.games) + int(a26.games),
            rate,
            True,
        ),
    ]

    L = []
    L.append("# Baseline Findings: Argentina (2022 + 2026) vs World Cup History\n")
    L.append("_Generated by `src/baseline_comparison.py`. Sources in `data/SOURCES.md`._\n")

    L.append("## The control group\n")
    L.append(
        f"- Modern (VAR-era) baseline penalty rate: **{rate:.3f} penalties per team per match** "
        "(pooled from the 2018 and 2022 World Cups: 52 penalties across 256 team-matches). "
        "This is the fair yardstick because 2026 also uses VAR.\n"
    )

    L.append("## Lens 1 — Rate test (Poisson)\n")
    L.append("| Subject | Penalties | Games | Expected | Fold | P(X ≥ obs) | Significant? |\n")
    L.append("|---|---|---|---|---|---|---|\n")
    for r in rows:
        sig = "**YES**" if r["p"] < 0.05 else "no"
        star = " *(provisional)*" if r["provisional"] else ""
        L.append(
            f"| {r['label']}{star} | {r['pens']} | {r['games']} | {r['expected']:.2f} | "
            f"{r['fold']:.1f}x | {r['p']:.4f} | {sig} |\n"
        )
    L.append("\n")

    L.append("**Reading the table honestly:**\n")
    L.append(
        f"- **2022 is a hard outlier** — ~{rows[0]['fold']:.1f}x the expected penalties, "
        f"p = {rows[0]['p']:.4f}. Real, not noise.\n"
        f"- **2026 alone is NOT significant** (p = {rows[1]['p']:.3f}). Argentina are again "
        f"getting penalties above the baseline rate (~{rows[1]['fold']:.1f}x), but 5 games is a "
        "small sample — this could easily be chance on its own.\n"
        f"- **Pooling both tournaments** ({rows[2]['pens']} penalties in {rows[2]['games']} games) "
        f"stays significant (p = {rows[2]['p']:.4f}): the pattern is driven by 2022 but 2026 "
        "does not contradict it.\n"
    )

    L.append("## Lens 2 — The all-time record\n")
    r_sorted = recs.sort_values("penalties_awarded", ascending=False)
    L.append(
        "Across every team in every World Cup, the most penalties ever awarded to a single "
        "team in one edition:\n\n"
    )
    L.append("| Team | Edition | Penalties |\n|---|---|---|\n")
    for _, row in r_sorted.iterrows():
        prov = " *(ongoing)*" if row.provisional == "yes" else ""
        L.append(f"| {row.team} | {row.edition}{prov} | {row.penalties_awarded} |\n")
    L.append(
        "\n- Before 2022, **no team in ~90 years of World Cups had been awarded more than 4** "
        "penalties in a single edition (Netherlands 1978, Portugal 1966).\n"
        "- Argentina's **5 in 2022 is the all-time record** — the single most extreme "
        "team-tournament ever recorded. Empirically, that is the 100th percentile.\n"
    )

    L.append("## The 2026 twist (and why it matters for honesty)\n")
    L.append(
        f"- Argentina were awarded ~{int(a26.pens_for)} penalties in their first {int(a26.games)} "
        "games of 2026 — but **Messi missed both**, becoming the first player to miss two "
        "penalties in a single World Cup.\n"
        "- This cleanly separates two claims people conflate: **'Argentina gets the calls'** "
        "(the awards suggest: yes, again) vs **'Argentina always benefits'** (2026 says: not "
        "automatically — they fluffed both). A rigging narrative that ignores the misses is "
        "dishonest.\n"
    )

    L.append("## Bottom line\n")
    L.append(
        "- On penalties **awarded**, Argentina is a real historical outlier: the all-time "
        "single-tournament record (2022) and an above-baseline rate again in 2026.\n"
        "- That outlier is **statistically significant when you pool the evidence**, but 2026 "
        "on its own is not — and the missed 2026 penalties show 'favored on calls' is not the "
        "same as 'gifted results'.\n"
        "- **Significance is not intent.** Style of play (a possession-heavy side that attacks "
        "the box) and deep tournament runs both inflate penalty counts. This analysis proves an "
        "anomaly; it does not, by itself, prove bias.\n"
    )

    (REPORTS / "BASELINE_FINDINGS.md").write_text("".join(L))
    print("".join(L))

    # ---- Figure: all-time record distribution ----
    fig, ax = plt.subplots(figsize=(7.5, 4.4))
    r_sorted2 = recs.sort_values("penalties_awarded")
    labels = [f"{t}\n{e}" for t, e in zip(r_sorted2.team, r_sorted2.edition)]
    colors = [ACCENT if t == "Argentina" else GREY for t in r_sorted2.team]
    ax.bar(labels, r_sorted2.penalties_awarded, color=colors)
    for i, v in enumerate(r_sorted2.penalties_awarded):
        ax.text(i, v + 0.05, str(int(v)), ha="center", fontweight="bold")
    ax.set_ylabel("Penalties awarded in one World Cup")
    ax.set_title("Most penalties awarded to a single team in one World Cup (all-time)",
                 fontweight="bold")
    fig.tight_layout()
    fig.savefig(FIG / "alltime_record.png", dpi=150)
    plt.close(fig)

    # ---- Figure: observed vs expected, both tournaments ----
    fig, ax = plt.subplots(figsize=(7.5, 4.4))
    labels = ["2022\nexpected", "2022\nactual", "2026\nexpected", "2026\nactual (prov.)"]
    vals = [rows[0]["expected"], rows[0]["pens"], rows[1]["expected"], rows[1]["pens"]]
    cols = [ARG_BLUE, ACCENT, ARG_BLUE, ACCENT]
    ax.bar(labels, vals, color=cols)
    for i, v in enumerate(vals):
        ax.text(i, v + 0.05, f"{v:.1f}" if v % 1 else f"{int(v)}", ha="center", fontweight="bold")
    ax.set_ylabel("Penalties awarded")
    ax.set_title("Argentina vs the VAR-era baseline: more penalties than expected, both years",
                 fontweight="bold")
    fig.tight_layout()
    fig.savefig(FIG / "baseline_observed_vs_expected.png", dpi=150)
    plt.close(fig)

    # ---- Figure: 2026 awarded vs converted ----
    fig, ax = plt.subplots(figsize=(6.5, 4.2))
    ax.bar(["Awarded", "Converted"], [int(a26.pens_for), int(a26.pens_converted)],
           color=[ACCENT, ARG_NAVY])
    for i, v in enumerate([int(a26.pens_for), int(a26.pens_converted)]):
        ax.text(i, v + 0.03, str(v), ha="center", fontweight="bold")
    ax.set_ylabel("Penalties")
    ax.set_title("The 2026 twist: Argentina got the calls, Messi missed them all",
                 fontweight="bold")
    ax.set_ylim(0, max(2, int(a26.pens_for)) + 0.6)
    fig.tight_layout()
    fig.savefig(FIG / "twenty26_awarded_vs_converted.png", dpi=150)
    plt.close(fig)

    print("\nWrote reports/BASELINE_FINDINGS.md and 3 figures to figures/.")


if __name__ == "__main__":
    main()
